version: "3.8"

services:
  caddy:
    image: "abiosoft/caddy:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
    networks:
      - ipApp
  # db:
  #   environment:
  #     POSTGRES_USER: ${USER}
  #     POSTGRES_PASSWORD: ${PASSWORD}
  #     POSTGRES_DB: ${DB}
  #   image: postgres:latest
  #   ports:
  #     - "${POSTGRES_PORT}:5432"
  #   restart: always
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - ipApp

  # backend:
  #   build:
  #     context: "./backend"
  #     dockerfile: Dockerfile
  #   environment:
  #     POSTGRES_USER: ${USER}
  #     POSTGRES_PASSWORD: ${PASSWORD}
  #     POSTGRES_DB: "db"
  #     APPLICATION_DB: ${APPLICATION_DB}
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #   hostname: backend
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./backend:/usr/src/backend
  #   depends_on:
  #     - db
  #   tty: true
  #   networks:
  #     - ipApp

  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    environment:
      - url=https://www.menilek.tech
      # - BACKEND_BUILD_TIME_URL: backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/frontend
    # depends_on:
    #   - caddy
    networks:
      - ipApp

networks:
  ipApp:
    driver: bridge
    external: true
#  docker-compose up --build -d
#  docker-compose exec backend python manage.py create_db
#  docker-compose exec backend python ./manage.py db psql -U menilek
#  docker-compose build --no-cache
#  docker-compose up -d
#  docker-compose down -v --rmi local
