version: "3.8"

services:
  backend:
    build: "./backend"
    ports:
      - "5000:5000"
    tty: true
  frontend:
    build: "./frontend"
    ports:
      - "80:80"
    depends_on:
      - backend
#  docker-compose up --build -d
#  docker-compose down -v --rmi local
